### ISSUE TITLE
gyp & npm errors building on Slackware64 14.2

### ISSUE THREAD

**Issue by dchmelik** [JoyStream/joystream-desktop#574]
On Slackware64 14.2 up-to-date stable, I get lots of [errors](https://gist.github.com/dchmelik/5952dcba6ba770068eaf0ec4648c7791) building this.  During the process (not all of which has output I pasted here) I noticed enough to know it seems you and/or the dependency writers haven't really explained enough, but (as not a JavaScript programmer) not enough to really know what happened.

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib64/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.88
gyp ERR! command "/usr/bin/node" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/joystream-electron/node_modules/joystream-node
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: appdmg@^0.4.5 (node_modules/electron-installer-dmg/node_modules/appdmg):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for appdmg@0.4.5: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN joystream@0.5.2 No repository field.
npm ERR! Linux 4.4.88
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! joystream-node@0.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the joystream-node@0.1.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the joystream-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs joystream-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls joystream-node
npm ERR! There is likely additional logging output above.

**Comment by bedeho** [comment]
Hi, thanks for this, we certainly have not tried to build the `joystream-node` native dependency on your platform before, perhaps thats part of the problem, may be a bit hard for us to reproduce on our end. I'll leave it to @mnaamani to decide, he maintains the build system for the dependency.

**Comment by mnaamani** [comment]
I don't see a clear error message in the log.
However I suspect the problem might be that the version of node might not be supported, not the particular flavor of linux.
Could you try building with node v7 and report back what you find?

**Comment by mnaamani** [comment]
Also as make sure to use conan 'v0.28.1` not newer.. as that breaks the build.
